Ni = pyip.inputInt("N : ")
# Po = pyip.inputInt("P : ")
# Ka = pyip.inputInt("K : ")
# temperature = pyip.inputFloat("Temperature : ")
# humidity = pyip.inputFloat("Humidity : ")
# ph = pyip.inputFloat("pH : ")
# rainfall = pyip.inputFloat("Rainfall : ")
